#!/usr/bin/env bash

work_home=$1

launchd_des_file=~/Library/LaunchAgents/com.1wenlong.server.plist
if [ -f "$launchd_des_file" ]; then
    launchctl unload $launchd_des_file
    echo "service unload: com.1wenlong.server"
    rm -f $launchd_des_file
    echo "service removed: $launchd_des_file"
fi
echo "server stop！"